server:
  port: 9090
spring:
  cloud:
    gateway:
      routes:
        - id: authService
          uri: http://localhost:9091
          predicates:
            - Path=/auth/**
        - id: productService
          uri: http://localhost:9092
          predicates:
            - Path=/product/**    
        - id: cartService
          uri: http://localhost:9093
          predicates:
            - Path=/cart/**
        - id: orderService
          uri: http://localhost:9094
          predicates:
            - Path=/order/**
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*" 
            allowedMethods:
              - POST
              - GET
              - OPTIONS
              - PUT 
              - DELETE